name: Run Real Time Data

permissions:
  contents: write

on:
  schedule:
    - cron: "0 * * * *"  
  workflow_dispatch:      # Para ejecutarlo manualmente

jobs:
  real_time:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0 
          ref: main

      - name: Configurar Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          environment-name: myenv
          python-version: '3.10'
          channels: conda-forge

      - name: Instalar dependencias y run Real Time 
        shell: bash -l {0}
        run: |
          conda install -y pip papermill ipykernel pandas numpy scikit-learn yfinance
          pip install backtesting
          python -m ipykernel install --user --name python3
          mkdir -p data
          papermill downLoadDataRealtimeAlpha.ipynb downLoadDataRealtimeAlpha_out.ipynb -k python3
      
      - name: Commit y push de archivos actualizados
        if: ${{ always() }}
        shell: bash
        run: |
          # Configura el usuario de commit
          git config user.name "LinderCa"
          git config user.email "casaslinder@gmail.com"
          # Añade los ficheros de data modificados
          git add data/dataxd.txt data/dataxh.txt
          # Sólo commit si hay cambios
          git diff --cached --quiet || git commit -m "🔄 Actualiza datos en dataxd y dataxh"
          # Push a main
          git push origin main
   